export const USER_ACTIVENAME = 'USER_ACTIVENAME';
export const USER_REQUEST = 'USER_REQUEST';
export const USER_FAILURE = 'USER_FAILURE';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_REP_SUCCESS = 'USER_REP_SUCCESS';
export const USER_STARS_SUCCESS = 'USER_STARS_SUCCESS';
export const USER_FOLLOWERS_SUCCESS = 'USER_FOLLOWERS_SUCCESS';
export const USER_FOLLOWINGS_SUCCESS = 'USER_FOLLOWINGS_SUCCESS';