export const SEARCH_ITEMS = 'SEARCH_ITEMS';
export const SEARCH_ACTIVENAME = 'SEARCH_ACTIVENAME';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';